version: '2.1'
services:
  mysql-db:
    image: mysql
    container_name: parking-reservation-mysql
    restart: always
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: parkingreservationDB
    volumes:
      - parking-reservation-mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - parking-reservation-net
  backend:
    image: backend
    container_name: parking-reservation-server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '50051:50051'
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - parking-reservation-net
  redis-publisher:
    image: redis
    container_name: redis-publisher
    command: ["redis-server", "--port", "6379"]
    ports:
      - "6379:6379"
    networks:
      - parking-reservation-net

networks:
  parking-reservation-net:

volumes:
  todo-mysql-data:
